general:
  prefix: "&b&lCoral&f&lDuels&r &r&8>>&r"
  debug: false

database:
  # sqlite | mysql
  type: "sqlite"
  database-name: "storage"
  ip-address: "localhost"
  port: 3306
  user: "root"
  password: ""

duel:
  request-expire-time: 30 # seconds
  block-commands: true
  commands-to-block:
    - "/spawn"
    - "/shop"
    - "/tpaccept"
    - "/home"
    - "/warp"
    - "/tpa"
    - "/tpahere"
    - "/duel"
    - "/duelaccept"
  allow-block-destruction: false
  allow-block-placement: false
  countdown-duration: 3


arena-wand:
  item: "STONE_AXE"
  name: "&cArena Wand"
  lore:
    - ""
    - "&7Usa questo oggetto per"
    - "&7selezionare i due punti"
    - "&7di generazione dei giocatori"
    - "&7in questa arena."
    - ""
  glow: true