general:
  prefix: "&b&lCoral&f&lDuels&r &r&8>>&r"
  debug: false

database:
  # sqlite | mysql
  type: "sqlite"
  database-name: "storage"
  ip-address: "localhost"
  port: 3306
  user: "root"
  password: ""

duel:
  request-expire-time: 30 # seconds
  block-commands: true
  immediate-respawn: true
  spectate-on-end: true
  commands-to-block:
    - "/spawn"
    - "/shop"
    - "/tpaccept"
    - "/home"
    - "/warp"
    - "/tpa"
    - "/tpahere"
    - "/duel"
    - "/duelaccept"
  allow-block-destruction: false
  allow-block-placement: false
  countdown-duration: 3
  gamemode-settings:
    change-gamemode: true
    gamemode: "SURVIVAL"
    set-prev-gamemode-when-end: true
  teleport:
    teleport-back: true
    # If the above statement is set to false, the players will be teleported at the given location when game ends
    teleport-location:
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0
      world: world


arena-wand:
  item: "STONE_AXE"
  name: "&cArena Wand"
  lore:
    - ""
    - "&7Usa questo oggetto per"
    - "&7selezionare i due punti"
    - "&7di generazione dei giocatori"
    - "&7in questa arena."
    - ""
  glow: true